### ISSUE TITLE
Body Structure Identifier 

### ISSUE THREAD

**Issue by goelalex** [HL7/fhir-mCODE-ig#186]
https://build.fhir.org/ig/HL7/fhir-mCODE-ig/StructureDefinition-mcode-tumor-specimen.html

Is the body structure already accurately represented by Specimen.type + Specimen.bodyStructure? 

Also Specimens are often sliced into smaller specimens, recommend making Specimen.parent MustSupport.

**Comment by markkramerus** [comment]
Hi Alex, 
It is true that the specimen body site can in theory be associated with a tumor at the same body site. Finding that tumor via the body site seems a bit brittle, while the identifier is how it currently happens in practice. Plus, it is more direct and less brittle. So we have decided to keep this in place, and if it turns out to be "belt plus suspenders" no harm is done.
